### ISSUE TITLE
When i start the script it instantly close himself

### ISSUE THREAD

**Issue by Freezen2** [sj-dan/OpenSea-NFT-Stealer#10]
When i start the script it instantly close himself and create the images folder but there is no image in it. 

In the image folder created i have the name of the collection folder>image_data but nothing in it like no image are in. How to fix it ?

I double checked, I have all the Prerequisites.

**Comment by samuelbailey123** [comment]
Check a different Collection Name or you could need to add headers.

**Comment by Freezen2** [comment]
I checked with a different Collection Name and it still doesn't work. 
What do you mean by "add headers" ? How can I do that, what should i do ?

**Comment by samuelbailey123** [comment]
It's been pulled into master just pull the latest and it should work for you

**Comment by samuelbailey123** [comment]
@sj-dan Let's close this

**Comment by Freezen2** [comment]
> It's been pulled into master just pull the latest and it should work for you

Ok, so I'm sorry but I didn't undertsand what you've said i'm not really experienced with coding so can you re-explain in a simple way so I can understand please ? (sorry about that)

**Comment by samuelbailey123** [comment]
https://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository
You're gonna wanna learn this stuff first

**Comment by Freezen2** [comment]
ok so the thing is i followed your guide i create a folder and in it i used the command git clone https://github.com/sj-dan/OpenSea-NFT-Stealer.git and after that i did all the thing you said  in the guide but it doesn't work, I have the same problem as in the issue #16 and when i re clicked on the script it create the image folder but nothing in it as i said above. So what should i do (i read what you've send me but it didn't helped me.).

**Comment by samuelbailey123** [comment]
@Freezen2 
`git clone https://github.com/sj-dan/OpenSea-NFT-Stealer.git `
`cd ./OpenSea-NFT-Stealer.git`

change line 9 to the collection name you want to download inside of the quotes that say "Collection Name"
`python3 ./opensea.py`

If you get a module not installed error then you need to install them with pip
`pip install requests`
`pip install random_user_agent`

**Comment by Freezen2** [comment]
Fixed my self, that was because there was an issue in my git
