### ISSUE TITLE
Q | What is image_data file folder usable as?

### ISSUE THREAD

**Issue by zhincic** [sj-dan/OpenSea-NFT-Stealer#14]
<img width="633" alt="Screenshot 2022-01-18 at 07 12 51" src="https://user-images.githubusercontent.com/90480378/149880913-ba355650-0204-4146-96fb-2914499446b3.png">

**Comment by samuelbailey123** [comment]
https://erickhun.com/posts/nft-misconception-image-arent-on-blockchains/

@sj-dan Let's close this issue

**Comment by sj-dan** [comment]
@zhincic It's just the JSON from the OpenSea API. If you don't want to use it, don't. If you need it, use it.
