### ISSUE TITLE
Exception has occurred: JSONDecodeError

### ISSUE THREAD

**Issue by kyuchin** [sj-dan/OpenSea-NFT-Stealer#19]
Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

  File "C:\1\1\1\OpenSea-NFT-Stealer-master\opensea.py", line 71, in <module>
    data = json.loads(requests.get(f"https://api.opensea.io/api/v1/assets?order_direction=asc&offset={offset}&limit=50&collection={CollectionName}&format=json", headers=headers).content.decode())

**Comment by sj-dan** [comment]
@kyuchin Please post the entire error. Also, provide additional info (i.e. what collection were you trying to download)?

**Comment by kyuchin** [comment]
its all error

**Comment by kyuchin** [comment]
its working rn can i ask can we get traits pic without all picture?

**Comment by sj-dan** [comment]
@kyuchin Not sure what you mean by 
> traits pic without all picture
