### ISSUE TITLE
Can this code also include downloading the json files?

### ISSUE THREAD

**Issue by shwin0x** [sj-dan/OpenSea-NFT-Stealer#2]

**Comment by sj-dan** [comment]
What exactly do you mean, the json file? Do you mean the JSON surrounding each individual NFT?

For example, if the API returns the following:

```{
"assets": [
  {
    "token_id": 1,
    "image_url": "https://example.com/image.png",
    "name": "random name",
    "price": "50ETH"
  }
]
```

What do you want the JSON file to output?

**Comment by shwin0x** [comment]
Yea. The individual json files associated with each images.

**Comment by shwin0x** [comment]
I mean evey image will have an associated json like what you have described above. Can that also be downloaded?

**Comment by sj-dan** [comment]
All done. The program will now create a subfolder called `image_data`. Inside this, it will create numbered json files (i.e. `5620.json`) corresponding to its respective NFT.

**Comment by shwin0x** [comment]
Thanks
