### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ghost** [sj-dan/OpenSea-NFT-Stealer#25]
Traceback (most recent call last):
  File "C:/Users/Kemal/Desktop/OpenSea-NFT-Stealer-master/OpenSea-NFT-Stealer-master/opensea.py", line 135, in <module>
    image_url = ipfs_resolve(image_url).url
  File "C:/Users/Kemal/Desktop/OpenSea-NFT-Stealer-master/OpenSea-NFT-Stealer-master/opensea.py", line 92, in ipfs_resolve
    cid = image_url.removeprefix("ipfs://")
AttributeError: 'str' object has no attribute 'removeprefix'

this error, some collections work, some give this exact error . thanks for your great code

**Comment by sj-dan** [comment]
What version of Python are you running? `str.removeprefix` was added in Python 3.9. Please update your Python and let me know if that fixes it.

**Comment by ghost** [comment]
Works amazing now once I updates to 3.10 , thanks

**Comment by ghost** [comment]
Is there a way to download only images and not meta data? Which lines of code should I comment /delete?

**Comment by sj-dan** [comment]
> Is there a way to download only images and not meta data? Which lines of code should I comment /delete?

Remove lines 111-120.
