### ISSUE TITLE
Same script for Magic Eden?

### ISSUE THREAD

**Issue by aborriginal** [sj-dan/OpenSea-NFT-Stealer#26]
Hello! Great script, working like a charm!
Can you modify your script so it can download images from Magic Eden? No API though...

**Comment by sj-dan** [comment]
The name of this repository and project is **OpenSea** NFT Stealer. I can make a separate script for Magic Eden. However, this isn't a valid issue for this repo.

**Comment by aborriginal** [comment]
I just did not get how to contact to you directly. If you can DM me - we can discuss.

**Comment by aborriginal** [comment]
Maybe you can contact me at telegram balda8?

**Comment by sj-dan** [comment]
@rokii666 You can reach me at my email listed on my GitHub, or my Discord DanChan#6969.

**Comment by aborriginal** [comment]
Sent you request in Discord

**Comment by aborriginal** [comment]
Hello! Are you still willing to do same script for MagicEden?
