### ISSUE TITLE
AttributeError: 'str' object has no attribute 'removeprefix'

### ISSUE THREAD

**Issue by aborriginal** [sj-dan/OpenSea-NFT-Stealer#28]
Beginning download of "boredapeyachtclub" collection.

#0000:
  Data  -> [✓] (Already Downloaded)
Traceback (most recent call last):
  File "opensea.py", line 135, in <module>
    image_url = ipfs_resolve(image_url).url
  File "opensea.py", line 92, in ipfs_resolve
    cid = image_url.removeprefix("ipfs://")
AttributeError: 'str' object has no attribute 'removeprefix'

**Comment by sj-dan** [comment]
Please read the setup instructions carefully. They ask for Python version **3.9 or above**.
