### ISSUE TITLE
Downloading not all items from collection

### ISSUE THREAD

**Issue by aborriginal** [sj-dan/OpenSea-NFT-Stealer#29]
Hi!
Collection name is CLONE X, there are 18716 items. OS Stealer downloads max 10050 and stops. Tried about 3 times with same result.

I also tried to add starting point in range function, which not helped:

Iterate through every unit
for i in range(**201**, iter):
    offset = i * 50
    data = json.loads(requests.get(f"https://api.opensea.io/api/v1/assets?order_direction=asc&offset={offset}&limit=50&collection={CollectionName}&format=json", headers=headers).content.decode())

**Comment by sj-dan** [comment]
@rokii666 Looks like OpenSea limits the `offset` URL parameter to 10,000. I'm looking into a workaround for this right now.
