### ISSUE TITLE
Error while running opensea.py

### ISSUE THREAD

**Issue by jimmy24599** [sj-dan/OpenSea-NFT-Stealer#41]
I installed the requirements.txt but when I run the file opensea.py I keep getting this error

Traceback (most recent call last):
  File "C:\Users\S\Desktop\OpenSea-NFT-Stealer-master\opensea.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by unknownsrc** [comment]
To fix this just do `pip install requests`

**Comment by sj-dan** [comment]
@jimmy24599 Not sure why that happens. The `requests` module is in the requirements.txt. I don't know how you installed requirements.txt but are still missing the `requests` module.
