### ISSUE TITLE
Download Stops

### ISSUE THREAD

**Issue by Soliidz** [sj-dan/OpenSea-NFT-Stealer#43]
Im trying to downlaod this

**Comment by sj-dan** [comment]
Please provide more details!

**Comment by gdelolmo7** [comment]
I have the same problem, the download stops at a certain point but doesn't show any message. For resuming the download I have to create a second terminal and re-run de command, but now I've done that several times and doesn't resume the download.  Any idea on how to fix this or make all the downloads go in one go?
