### ISSUE TITLE
Image Size - High / Low

### ISSUE THREAD

**Issue by sepa-rater** [sj-dan/OpenSea-NFT-Stealer#47]
When I use a previous version of this script it pumps out 4000x4000px images. 
When I use the latest version of this script the images come out at 512x512px.
This is running the scripts on the same collection.

I wonder if this was a decision that was made?
The new script runs a lot faster and hangs up less, however because I am creating a massive poster graphic collage of all the images, for this I prefer the larger images and will wait longer for the script to run as necessary.  

If there was a change made in how the images are downloaded, I wonder if both options could be made available when running the script? eg. download High OR Low Res images...

"python3 opensea.py collection-name HIGH" something like that?!?!?

Cheers.

**Comment by sj-dan** [comment]
Very sorry. Turns out one of the commits made by someone else (specifically e652973) changed the way that the script works without my knowledge. The issue has been fixed in 3bac9b6.
