### ISSUE TITLE
Null

### ISSUE THREAD

**Issue by z3Nsk1Fh5a** [sj-dan/OpenSea-NFT-Stealer#7]
Used Notepad++ to change the collection, double clicked to see a brief black terminal appear for a split second then nothing occurs.

**Comment by z3Nsk1Fh5a** [comment]
#0104:
  Data  -> [✓] (Successfully downloaded)
  Image -> [✓] (Successfully downloaded)

#0065:
  Data  -> [✓] (Successfully downloaded)
---------------------------------------------------------------------------
InvalidSchema                             Traceback (most recent call last)
<ipython-input-1-4229e1e5cdb3> in <module>()
     85             # Make the request to the URL to get the image
     86             if not asset["image_original_url"] == None:
---> 87               image = requests.get(asset["image_original_url"])
     88             else:
     89               image = requests.get(asset["image_url"])

4 frames
/usr/local/lib/python3.7/dist-packages/requests/sessions.py in get_adapter(self, url)
    726 
    727         # Nothing matches :-/
--> 728         raise InvalidSchema("No connection adapters were found for {!r}".format(url))
    729 
    730     def close(self):

InvalidSchema: No connection adapters were found for 'ipfs://

**Comment by krewella1** [comment]
why was this closed before an answer? is there any solution to this problem?

**Comment by sj-dan** [comment]
> why was this closed before an answer? is there any solution to this problem?

Not sure who closed this issue early (wasn't me), but it was fixed in commit a88ca55.

**Comment by krewella1** [comment]
> > why was this closed before an answer? is there any solution to this problem?
> 
> Not sure who closed this issue early (wasn't me), but it was fixed in commit a88ca55.

ok, thanks for the feedback.
